services:
  vaultwarden:
    image: "vaultwarden/server:latest"
    container_name: "vaultwardenfinallversion"
    restart: unless-stopped
    environment:
     - ADMIN_TOKEN: "$$argon2id$$v=19$$m=65540,t=3,p=4$$ZjJleEhQMld5WFlIbkFMQkY1L0tvMEVZLzlWZjhYT0VLa0dtNXdMZTY0WT0$$CKamsIU5TVwaatyAVco+f7OYF95GegfEulxnd7airiQ"
    volumes:
      - ./vw-data/:/data/
    ports:
      - "801:80"
    networks:
      vaultwarden_network:
        ipv4_address: 10.10.10.3

networks:
  vaultwarden_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1