services:
  vaultwarden:
    image: "vaultwarden/server:latest"
    container_name: "vaultwardenfinallversion"
    restart: unless-stopped
    environment:
      - ADMIN_TOKEN: "HASLO"
    volumes:
      - ./vw-data/:/data/
    ports:
      - "801:80"
    networks:
      vaultwarden_network:
        ipv4_address: 10.10.10.3

networks:
  vaultwarden_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1